parameters:
    novae_zseo.default.robots_disallow: []
    novae_zseo.default.google_verification: ~
    novae_zseo.default.sitemap_excludes:
        locations: []
        subtrees: []
        contentTypeIdentifiers: ['plopix']
    novae_zseo.default.default_metas:
        author: "eZ Community Bundle Nova eZ SEO Bundle"
        copyright: ~
        generator: "eZ Platform"
        MSSmartTagsPreventParsing: "TRUE"
    novae_zseo.default.default_links:
        Index:
            href: { location_id: 2 }
            title: 'Home'
#        Top:
#            href: { route : 'route_name' }
#            title: 'Home'
        Search:
            href: { legacy_uri: '/content/advancedsearch' }
            title: 'Search'
        'Shortcut icon':
            href: { asset: '/design/standard/images/favicon.ico' }
            type: 'image/x-icon'
        Alternate:
            href: { legacy_uri: '/rss/feed/my_feed' }
            title: 'RSS'
            type: 'application/rss+xml'
    novae_zseo.default.fieldtype_metas_identifier: "metas"
    novae_zseo.default.fieldtype_metas:
        title:
            label: 'Title'
            default_pattern: "<title|name>"
            icon: 'book'
        description:
            label: 'Description'
            default_pattern: ~
            icon: 'book'
        keywords:
            label: 'Keywords'
            default_pattern: ~
            icon: 'tags'
        'canonical':
            label: 'External Canonical URL'
            default_pattern: ~
            icon: 'link'
        'og:title':
            label: 'Title'
            default_pattern: "<title|name>"
            icon: 'facebook-official'
        'og:description':
            label: 'Descrition'
            default_pattern: "<short_descrition|description|title|name>"
            icon: 'facebook-official'
        'og:image':
            label: 'Image'
            default_pattern: "<image|picture>"
            icon: 'facebook-official'
        'twitter:title':
            label: 'Title'
            default_pattern: "<title|name>"
            icon: 'twitter-square'
        'twitter:description':
            label: 'Descrition'
            default_pattern: "<short_descrition|description|title|name>"
            icon: 'twitter-square'
        'twitter:image':
            label: 'Image'
            default_pattern: "<image|picture>"
            icon: 'twitter-square'