system:
    default:
        yui:
            modules:
                ez-rawcontentview:
                    requires:
                        - 'novaseometas-view'
                ez-contenteditformview:
                    requires:
                        - 'novaseometas-editview'
                novaseometas-view:
                    requires: ['ez-fieldview', 'novaseometasview-ez-template', 'meta-view']
                    path: "%ezseobundle.public_dir%/js/views/fields/novaseometas-view.js"
                novaseometas-editview:
                    requires: ['ez-fieldeditview', 'event-valuechange', 'novaseometaseditview-ez-template', 'meta-editview']
                    path: "%ezseobundle.public_dir%/js/views/fields/novaseometas-editview.js"
                novaseometasview-ez-template:
                    type: 'template'
                    path: "%ezseobundle.public_dir%/templates/fields/view/novaseometas.hbt"
                novaseometaseditview-ez-template:
                    type: 'template'
                    path: "%ezseobundle.public_dir%/templates/fields/edit/novaseometas.hbt"
                meta-view:
                    requires: ['ez-templatebasedview', 'metaview-ez-template']
                    path: "%ezseobundle.public_dir%/js/views/value/meta-view.js"
                meta-editview:
                    requires: ['ez-fieldeditview', 'metaeditview-ez-template']
                    path: "%ezseobundle.public_dir%/js/views/value/meta-editview.js"
                metaview-ez-template:
                    type: 'template'
                    path: "%ezseobundle.public_dir%/templates/value/view/meta.hbt"
                metaeditview-ez-template:
                    type: 'template'
                    path: "%ezseobundle.public_dir%/templates/value/edit/meta.hbt"




