parameters:
    novactive.novaseobundle.admin_user_id: 14
    novactive.novaseobundle.meta_field_name: Metas
    novactive.novaseobundle.meta_field_description: Metas for Search Engine Optimizations
    novactive.novaseobundle.meta_field_group: novaseo

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $entityManager: "@novaezeo.doctrine.entity_manager"

    # Marking fieldtype as unindexable for ibexa platform solr bundle to stop errors
    novactive.novaseobundle.field_type.novaseometas.indexable.unindexed:
        class: Ibexa\Core\FieldType\Unindexed
        tags:
            - { name: ibexa.field_type.indexable, alias: novaseometas }

    Novactive\Bundle\eZSEOBundle\Core\FieldType\Metas\MetasStorage:
        arguments:
            $gateway: '@Novactive\Bundle\eZSEOBundle\Core\FieldType\Metas\MetasStorage\Gateway\DoctrineStorage'
        public: true
        tags:
            - { name: ibexa.field_type.storage.external.handler, alias: novaseometas }

    Novactive\Bundle\eZSEOBundle\Core\FieldType\Metas\MetasStorage\Gateway\DoctrineStorage:
        arguments:
            $connection: "@ibexa.api.storage_engine.legacy.connection"

    Novactive\Bundle\eZSEOBundle\Core\FieldType\Metas\Converter:
        tags:
            - { name: ibexa.field_type.storage.legacy.converter, alias: novaseometas, lazy: true, callback: '::create' }

    Novactive\Bundle\eZSEOBundle\Core\FieldType\Metas\FormMapper:
        tags:
            - { name: ibexa.admin_ui.field_type.form.mapper.definition, fieldType: novaseometas }
            - { name: ibexa.admin_ui.field_type.form.mapper.value, fieldType: novaseometas }

    # OTHER SERVICES
    Novactive\Bundle\eZSEOBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
        bind:
            $fieldHelper: '@Ibexa\Core\Helper\FieldHelper'

    Novactive\Bundle\eZSEOBundle\Twig\NovaeZSEOExtension: ~
    Novactive\Bundle\eZSEOBundle\Core\DummyCustomFallback: ~

    Novactive\Bundle\eZSEOBundle\Core\MetaNameSchema:
        lazy: true
        arguments:
            $contentTypeHandler: "@Ibexa\\Contracts\\Core\\Persistence\\Content\\Type\\Handler"
            $languageHandler: "@Ibexa\\Core\\Persistence\\Cache\\ContentLanguageHandler"
            $translationHelper: "@Ibexa\\Core\\Helper\\TranslationHelper"
        calls:
            - [setRichTextConverter, ["@Ibexa\\FieldTypeRichText\\RichText\\Converter\\Html5"]]
            # Note: injecting lower layer Variation Handler (AliasGenerator) as a workaround for missing Public API objects context
            - [setImageVariationService, ["@ibexa.image_alias.imagine.alias_generator"]]

    Novactive\Bundle\eZSEOBundle\Core\Installer\Field:
        arguments:
            $metaFieldName: "%novactive.novaseobundle.meta_field_name%"
            $metaFieldDescription: "%novactive.novaseobundle.meta_field_description%"
            $metaFieldGroup: "%novactive.novaseobundle.meta_field_group%"

    Novactive\Bundle\eZSEOBundle\Command\AddNovaSEOMetasFieldTypeCommand:
        arguments:
            $adminUserId: "%novactive.novaseobundle.admin_user_id%"

    Novactive\Bundle\eZSEOBundle\Core\Converter\ContentTypesHelper: ~

    Novactive\Bundle\eZSEOBundle\Listener\AdminTopMenu:
        tags:
            - { name: kernel.event_listener, event: "ezplatform_admin_ui.menu_configure.main_menu", method: "onMenuConfigure",  priority: -100 }

    Novactive\Bundle\eZSEOBundle\Core\Helper\ImportUrlsHelper:
        $ioService: '@ezseo_importurls.ibexa.core.io_service'
        $cacheDirectory: '%kernel.cache_dir%'

    Novactive\Bundle\eZSEOBundle\Core\SiteAccessAwareEntityManagerFactory:
        arguments:
            $repositoryConfigurationProvider: "@Ibexa\\Bundle\\Core\\ApiLoader\\RepositoryConfigurationProvider"
            $resolver: "@doctrine.orm.default_entity_listener_resolver"
            $settings: { debug: "%kernel.debug%", cache_dir: "%kernel.cache_dir%" }

    novaezeo.doctrine.entity_manager:
        class: Doctrine\ORM\EntityManagerInterface
        factory: ['@Novactive\Bundle\eZSEOBundle\Core\SiteAccessAwareEntityManagerFactory', 'get']

    Novactive\Bundle\eZSEOBundle\Core\Sitemap\QueryFactory: ~

    Novactive\Bundle\eZSEOBundle\Core\UrlWildcardRouter:
        arguments:
            - '@ibexa.api.service.url_wildcard'
            - '@Ibexa\Core\MVC\Symfony\Routing\Generator\UrlAliasGenerator'
            - '@router.request_context'
        calls:
            - [setLogger, ['@?logger']]
            - [setWildcardService, ['@ibexa.api.service.url_wildcard']]
        tags:
            - { name: router, priority: 2000 }

    novactive.novaseobundle.form.type.meta:
        class: Novactive\Bundle\eZSEOBundle\Form\Type\MetaType
        arguments:
            - "%nova_ezseo.default.fieldtype_metas%"
        tags:
            - { name: form.type, alias: seos }
